on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: pkgci

jobs:
  pkgdown:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download and install
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("ErikaCantor/kslboruta")
        shell: Rscript {0}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      # - name: Deploy package
      #   run: |
      #     git config --local user.email "erika.cantor@postgrado.uv.cl"
      #     git config --local user.name "GitHub Actions"
      #     Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
